---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes

git_global_email: irvin@capagcuan.org
username: jcapagcuan

playground_path: ~/playground

dotfiles_repo: https://github.com/travis-south/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: "{{ playground_path }}/dotfiles"
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .vimrc
  - .gitconfig

powerline_fonts_repo: https://github.com/powerline/fonts.git
powerline_fonts_repo_local_destination: "{{ playground_path }}/powerline-fonts"

solarized_repo: https://github.com/lysyi3m/macos-terminal-themes.git
solarized_repo_local_destination: "{{ playground_path }}/macos-terminal-themes"

custom_scripts_repo: git@gitlab.com:travis-south/custom-scripts.git
custom_scripts_repo_local_destination: "{{ playground_path }}/custom-scripts"
custom_scripts_repo_key: ~/.ssh/id_rsa

post_provision_tasks:
  - tasks/other-packages.yml

extra_packages:
  - htop
  - git
  - zsh-history-substring-search
  - kubectl
  - docker-compose
  - python
  - qcachegrind
  - hashicorp/tap/boundary
  - awscli
  - composer
  - terraform
  - serverless
  - jq
  - mpv
  - youtube-dl
  - fzf
  - ssh-copy-id
  - phpbrew
  - wget
  - helm
  - istioctl
  - watch
  - bzip2
  - k9s
  - mercurial
  - kustomize
  - siege
  
extra_cask_packages:
  - docker
  - visual-studio-code
  - slack
  - skype
  - viber
  - private-internet-access
  - discord
  - lulu
  - do-not-disturb
  - knockknock
  - taskexplorer
  - reikey
  - netiquette
  - blockblock
  - ransomwhere
  - oversight
  - lockdown
  - zoomus
  - google-drive-file-stream
  - pgadmin4
  - vlc
  - postman
  - spotify
  - google-chrome
  - microsoft-teams
  - nordvpn
  - private-internet-access
  - onedrive
  - google-drive-file-stream
  - messenger
  - telegram
  - signal
  - adobe-acrobat-reader
  - send-to-kindle
  - lando
  - epoccam
  - obs
  - amethyst
  - openvpn-connect
  - sequel-pro
  - balenaetcher
  - firefox
  - blackhole-16ch

force_install: no
