---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes

playground_path: ~/playground

dotfiles_repo: https://github.com/travis-south/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: "{{ playground_path }}/dotfiles"
dotfiles_files:
  # - .zshrc
  - .gitignore
  - .inputrc
  - .vimrc
  - .gitconfig

post_provision_tasks: []

extra_packages:
  - htop
  - git
  - zsh-history-substring-search
  - kubectl

extra_cask_packages:
  - visual-studio-code
