---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes

playground_path: ~/playground

dotfiles_repo: https://github.com/travis-south/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: "{{ playground_path }}/dotfiles"
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .vimrc
  - .gitconfig

powerline_fonts_repo: https://github.com/powerline/fonts.git
powerline_fonts_repo_local_destination: "{{ playground_path }}/powerline-fonts"

post_provision_tasks: []

extra_packages:
  - htop
  - git
  - zsh-history-substring-search
  - kubectl
  - docker
  - docker-compose
  - yarn
  - python
  - qcachegrind
  - hashicorp/tap/boundary
  - awscli
  
extra_cask_packages:
  - docker
  - visual-studio-code
  - slack
  - skype
  - viber
  - private-internet-access
  - discord
  - lulu
  - do-not-disturb
  - knockknock
  - taskexplorer
  - reikey
  - netiquette
  - blockblock
  - ransomwhere
  - oversight
  - lockdown
  - zoomus
  - google-drive-file-stream
  - pgadmin4
  - vlc
  - postman
  - spotify
  - google-chrome
  - microsoft-teams

force_install: no
