---
- hosts: all
  connection: local

  vars_files:
    - default.config.yml

  vars_prompt:
    - name: "git_global_email"
      prompt: "Git email"
      private: no
      default: "irvin@capagcuan.org"
    - name: "username"
      prompt: "Username"
      private: no
      default: "jcapagcuan"

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - ../config.yml
      tags: ['always']
    - name: Remove dotfiles folder
      file:
        path: "{{ dotfiles_repo_local_destination }}"
        state: absent
    - name: Create playground folder
      file:
        path: "{{ playground_path }}"
        state: directory

  roles:
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
  
  tasks:
    - include: tasks/ansible-setup.yml

    - include: tasks/sudoers.yml
      when: configure_sudoers

    - name: Update git global config email
      git_config:
        name: user.email
        scope: global
        value: "{{ git_global_email }}"

    - include: tasks/extra-packages.yml
      tags: ['extra-packages']

    - name: Run configured post-provision ansible task files.
      include: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"

    - name: Copy custom zsh to ohmyzsh
      copy:
        src: ~/playground/dotfiles/custom.zsh
        dest: ~/.oh-my-zsh/custom/
