---
- name: Ensure Ansible downloads directory exists.
  file:
    path: "{{ downloads }}"
    state: directory

- name: Ensure /etc/ansible directory exists.
  file:
    path: /etc/ansible
    state: directory
  become: yes
  
- name: Check if /usr/local/etc/ansible exits
  stat:
    path: /usr/local/etc/ansible
  register: register_name

- name: Symlink /usr/local/etc/ansible to /etc/ansible.
  file:
    src: /etc/ansible
    path: /usr/local/etc/ansible
    state: link
  become: yes
  when: register_name.stat.exists
