---
- name: Install extra packages
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ extra_packages }}"
  become: no

- name: Install cask packages
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ extra_cask_packages }}"
  become: no
