---
- name: Install DebOps
  ansible.builtin.pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    virtualenv: "{{ ansible_env.HOME }}/venvs/debops_env"
    virtualenv_site_packages: yes
  with_items: "{{ python_libs }}"
  become: no
